export const LOAD_STATISTICS = "LOAD_STATISTICS";
export const LOAD_SOME_DATA = "LOAD_SOME_DATA";
export const LOAD_PLOT = "LOAD_PLOT";
export const LOAD_ALGORITHMS = "LOAD_ALGORITHMS";

export const TOGGLE_TOKEN = "TOGGLE_TOKEN";
export const TOGGLE_TISSUE_TYPE = "TOGGLE_TISSUE_TYPE";

export const UPDATE_EXPERIMENT_NAME = "UPDATE_EXPERIMENT_NAME";
