export const LOAD_STATISTICS = "LOAD_STATISTICS";
export const LOAD_SOME_DATA = "LOAD_SOME_DATA";
export const LOAD_PLOT = "LOAD_PLOT";
export const UPDATE_EXPERIMENT_NAME = "UPDATE_EXPERIMENT_NAME";
