export const LOAD_STATISTICS = "LOAD_STATISTICS";
export const LOAD_ALGORITHMS = "LOAD_ALGORITHMS";

export const TOGGLE_TOKEN = "TOGGLE_TOKEN";
export const TOGGLE_TISSUE_TYPE = "TOGGLE_TISSUE_TYPE";

export const UPDATE_EXPERIMENT_NAME = "UPDATE_EXPERIMENT_NAME";

export const CREATE_RUN = "CREATE_RUN";
export const START_ALGORITHM = "START_ALGORITHM";
export const ALGORITHM_DONE = "ALGORITHM_DONE";
